version: 2.1
jobs: 
  build: 
    docker: # run the steps with Docker
      - image: circleci/node:10.16.0
    steps: 
      - checkout 
      - run:
          name: install
          command: npm ci
      - run: 
          name: test
          command: npm test
      - store_artifacts: 
          path: test-results
          prefix: tests
      - store_artifacts: 
          path: coverage
          prefix: coverage
      - store_test_results: 
          path: test-results.xml
