version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs: 
  test: 
    docker: 
      - image: circleci/node:10.16.0
    steps: 
      - checkout 
      - run:
          name: install
          command: npm ci
      - persist_to_workspace:
          root: .
          paths: 
           - node_modules
      - run: 
          name: test
          command: npm test
      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts: 
          path: test_results
          prefix: tests
      - store_artifacts: 
          path: coverage
          prefix: coverage
      - store_test_results: 
          path: test_results
  build:
    docker: 
      - image: circleci/node:10.16.0
    steps: 
      - checkout
      - attach_workspace:
          at: . 
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: 
            - dist

  deploy:
    docker: 
      - image: circleci/node:10.16.0
    steps: 
      - checkout 
      - attach_workspace:
          at: .
      - store_artifacts: 
          path: dist
          prefix: dist


workflows:
  version: 2
  "Test, Build, Deploy":
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
            - build
